server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/migration/V1.0__creat_product.sql
    data: classpath:db/migration/V2.0__add_product.sql
    url: jdbc:mysql://localhost:3306/niumall?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  session:
    store-type: none
  flyway:
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
#Mybatis-plus的寻址方式
mybatis-plus:
  #mapper-locations: classpath:mapper/*.xml
  mapper-locations: com/**/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

#MyBatis的mapperxml的路径配置
#mybatis:
# mapper-locations:
#   - classpath:dao/*.xml]\
#   - classpath*:com/**/dao/*.xml
# configuration:
#    mapUnderscoreToCamelCase: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

#aliyun:
#  oss:
#    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
#    accessKeyId: test # 访问身份验证中用到用户标识
#    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
#    bucketName: macro-oss # oss的存储空间
#    policy:
#      expire: 300 # 签名有效期(S)
#    maxSize: 10 # 上传文件大小(M)
#    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
#    dir:
#      prefix: mall/images/ # 上传文件夹路径前缀
#
#minio:
#  endpoint: http://192.168.3.101:9090 #MinIO服务所在地址
#  bucketName: mall #存储桶名称
#  accessKey: minioadmin #访问的key
#  secretKey: minioadmin #访问的秘钥
management:
  health:
    redis:
      enabled: false
